### ISSUE TITLE
[Bug]: Trio websocket closing unexpectedly

### ISSUE THREAD

**Issue by mmm3bbb** [blocknative/python-sdk#33] opened 2022-01-07 02:36 UTC
### Current Behavior

After some time (a few hours), my app will die due to trio websockets closing a connection (see log below). This occurs both on macos and linux. Both environments have good network connectivity and other applications don't seem to be losing network.

### Expected Behavior

I would like some visibility or reconnection control so it doesn't die.

### Python Version

3.9

### Relevant log output

```shell
Traceback (most recent call last):
  File "/root/x/dex_mempool/x.py", line 190, in <module>
    start()
  File "/root/x/dex_mempool/x.py", line 176, in start
    liquidity_stream.connect()
  File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 162, in connect
    return trio.run(self._connect, base_url)
  File "/usr/local/lib/python3.9/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 318, in _connect
    await self._handle_connection(base_url)
  File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 312, in _handle_connection
    await self._connect(base_url)
  File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 318, in _connect
    await self._handle_connection(base_url)
  File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 308, in _handle_connection
    nursery.start_soon(self._message_dispatcher)
  File "/usr/local/lib/python3.9/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
trio.MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>

Details of embedded exception 1:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 201, in _poll_messages
      msg = await self._ws.get_message()
    File "/usr/local/lib/python3.9/site-packages/trio_websocket/_impl.py", line 873, in get_message
      raise ConnectionClosed(self._close_reason) from None
  trio_websocket._impl.ConnectionClosed

Details of embedded exception 2:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/blocknative/stream.py", line 277, in _heartbeat
      await self._ws.ping()
    File "/usr/local/lib/python3.9/site-packages/trio_websocket/_impl.py", line 897, in ping
      raise ConnectionClosed(self._close_reason)
  trio_websocket._impl.ConnectionClosed
```

**Comment by taylorjdawson** [comment] 2022-02-11 20:25
@mmm3bbb Going to take a look at this today, thanks for raising the issue and sorry for the delay!

**Comment by mmm3bbb** [comment] 2022-02-11 21:23
No worries. Thanks for taking a look. I've seen a few people post this issue on discord.

**Comment by mmm3bbb** [comment] 2022-02-11 21:27
Related to this, it would be great if there were a way to stop a stream, change its filter and restart it. Right now, I have to start a new process when I start a new stream and then terminate that process when I want to stop it (and create a new process with changed filter). Maybe there's a way to do that now that I'm not aware of.

**Comment by taylorjdawson** [comment] 2022-02-11 21:28
@mmm3bbb Do you happen to have timestamped logs of when this occurs? @mmm3bbb Can you DM me on discord and I can share an example of changing subscriptions that may help.

**Comment by taylorjdawson** [comment] 2022-02-11 21:50
Okay here is my preliminary analysis what is occurring. Based on this [SO thread](https://stackoverflow.com/a/68750272/9129466) it looks like 1006 close errors can occur due to network issues. At the time I can not definitively say whether it is a client side or server side network issue. Although based on what @mmm3bbb reported, his other applications seem to be functioning normally. This leads me to believe that there may be a server side issue where the close frame is not getting sent to the client websocket connection.

Client side the error get's thrown because when calling the methods `get_message()` or `ping()` if the connection is closed then a `ConnectionClosed` error gets raised. I can reproduce this locally by closing the connection on a mock ws server and then trying to call `ws.ping()` in the python script. When doing this, however, there is no close code. What I believe is happening is that when the client doesn't properly get the close frame from the server it closes the connection and sets the `trio_websocket.WebSocketConnection.closed` property with `CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>`. Then the code calls `get_message()` and `ping()` and that `ConnectionClosed` error gets called with that close reason set.

I believe the fix is to simply to check if the socket connection is open before calling these methods.

**Comment by taylorjdawson** [comment] 2022-02-13 06:39
@mmm3bbb please reopen if issue persists, thanks!

**Closed** 2022-02-13 06:39 UTC
Labels: bug
